export const UPDATE_BOOKS = 'UPDATE_BOOKS';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const SET_FAVORITES = 'SET_FAVORITES';
export const DELETE_FAVORITE_BOOK = 'DELETE_FAVORITE_BOOK';
